# Generated by Django 3.0.6 on 2020-06-02 18:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=15)),
                ('cat_icon', models.ImageField(max_length=255, upload_to='cat_images/')),
                ('cat_show', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=50)),
                ('recipe_img1', models.ImageField(max_length=255, upload_to='recipe_images/')),
                ('recipe_img2', models.ImageField(max_length=255, upload_to='recipe_images/')),
                ('recipe_img3', models.ImageField(max_length=255, upload_to='recipe_images/')),
                ('recipe_img4', models.ImageField(max_length=255, upload_to='recipe_images/')),
                ('recipe_des', models.CharField(max_length=1000)),
                ('recipe_ingredients', models.CharField(max_length=1000)),
                ('recipe_servings', models.CharField(max_length=1000, null=True)),
                ('recipe_sources', models.CharField(max_length=500, null=True)),
                ('recipe_preptime', models.CharField(max_length=50)),
                ('recipe_cooktime', models.CharField(max_length=50)),
                ('recipe_date', models.DateTimeField(default=datetime.datetime.now)),
                ('recipe_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.Category')),
                ('recipe_posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
