# Generated by Django 3.0.6 on 2020-06-15 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='lname',
        ),
    ]
